### PR TITLE
Add C API for adding lib. search path

### PR DESCRIPTION
**Pull request by rsetaluri**

### CODE REVIEW

**Comment by rsetaluri** [comment]
Depends on https://github.com/rdaly525/coreir/pull/881.

@rdaly525 we still need to call the actually api in __init__ or something. Would it be best to put it in __init__?

**Comment by leonardt** [comment]
A quick scan of https://github.com/rdaly525/coreir/blob/master/src/ir/dynamiclibrary.cpp, it doesn't seem like searchPaths is actually used for anything except as a "safety check" (there's code to look in the searchpaths to make sure you can find the library), but from what I can tell, it doesn't actually pass this information to dlopen or any other code (unless it does so implicitly or in another part of the codebase)

**Comment by leonardt** [comment]
See https://github.com/JuliaLang/julia/issues/3364 and https://github.com/JuliaLang/julia/commit/498e8babf052d06a8d6d1200eaf23f69297950e0 for an example of how we could do this.

Specifically, https://github.com/JuliaLang/julia/commit/498e8babf052d06a8d6d1200eaf23f69297950e0#diff-546cd044e18fcec4eed66dcdac75bfa2R107-R127

Looks like they iterate over a list of search paths, try loading the library with the explicit path, until dlopen doesn't return an error or they run out of paths to try.

**Comment by rsetaluri** [comment]
Interesting, yeah looks like `foundPath` is never actually used, and we just use `dlopen` flatly.

I honestly think if we're going to need to make a lot of modifications we should just use https://www.boost.org/doc/libs/1_64_0/doc/html/boost_dll.html. There's a lot of platform dependent stuff too that that library handles well.

For now I've hid the fast compile behind a flag that's turned off by default. I think we should just rethink the library loading stuff a bit if it's causing this many issues.

**Comment by leonardt** [comment]
FWIW, it looks like julia uses libuv for handling the dl logic (http://docs.libuv.org/en/v1.x/dll.html), not sure if there using it more generally but one alternative option (although the core of the library seems more oriented towards things unrelated to our use case like async IO)

**Comment by leonardt** [comment]
Is this still needed? Did we ever resolve this library loading issue?

**Comment by rsetaluri** [comment]
There are a still many issues, but I don't think this is going to help too much right now. Closing until we figure out more.

**Pull request closed without merging**
