### PR TITLE
Link

### PR DESCRIPTION
**Pull request by rdaly525**
Adds APIs for coreir linking/loading.
Depends on https://github.com/rdaly525/coreir/pull/998

Should fix broken master.

### CODE REVIEW

**Review by rsetaluri — APPROVED** [review]

**Comment by leonardt** [comment]
Looks like the latest release isn't working with magma https://travis-ci.org/github/phanrahan/magma/builds/766012960, have you tried this with the magma test suite? Maybe there's something we haven't covered in the test here.

**Comment by rdaly525** [comment]
@rsetaluri and I are debugging now. There were a couple of issues related to a new linking check (cannot link a definition to an existing module with a definition). Worst case is I can downgrade that check to a warning.

**Comment by rdaly525** [comment]
Basically this issue shows up if you save a file then immediately load the file again in the same context

**Comment by rsetaluri** [comment]
@rdaly525 @leonardt I think https://github.com/phanrahan/magma/pull/944/commits/4868acd6da0490ff405c5a53d5361af61d84c419 which is a part of https://github.com/phanrahan/magma/pull/944/ should fix. should be merged soon

**Comment by leonardt** [comment]
Seems like mantle is also failing now: https://travis-ci.org/github/phanrahan/mantle/builds/766019464, not sure if it's necessarily related but with the timing it may be.  It seems to be in the simulator though, not sure if there's any changes that would affect that?

**Comment by leonardt** [comment]
Upgrading the pycoreir version also breaks this test in fault:
```
~/repos/fault eq-and*
base ❯ pytest tests/test_tester/test_symbolic_tester.py::test_tester_magma_internal_signals_verilator
```
see also https://github.com/leonardt/fault/pull/305/checks?check_run_id=2291668273

**Comment by rdaly525** [comment]
> Seems like mantle is also failing now: https://travis-ci.org/github/phanrahan/mantle/builds/766019464, not sure if it's necessarily related but with the timing it may be. It seems to be in the simulator though, not sure if there's any changes that would affect that?

@rsetaluri is this fixed with your simulator changes to magma?

**Comment by rdaly525** [comment]
> Upgrading the pycoreir version also breaks this test in fault:
> 
> ```
> ~/repos/fault eq-and*
> base ❯ pytest tests/test_tester/test_symbolic_tester.py::test_tester_magma_internal_signals_verilator
> ```
> 
> see also https://github.com/leonardt/fault/pull/305/checks?check_run_id=2291668273

Ill investigate

**Comment by rsetaluri** [comment]
@rdaly525 simulator changes were merged into magma; perhaps not released

**Comment by rdaly525** [comment]
That fault test is working for me locally with coreir/pycoreir master.

**Comment by rsetaluri** [comment]
i think @leonardt did a merge recently though

**Pull request merged**
